# Generated by Django 5.0.7 on 2024-07-17 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userModel", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reguser",
            old_name="birthday",
            new_name="birthdate",
        ),
    ]
