# Generated by Django 5.0.7 on 2024-07-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userModel", "0002_rename_birthday_reguser_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reguser",
            name="gender",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="reguser",
            name="password",
            field=models.CharField(max_length=256),
        ),
    ]
