# Generated by Django 5.0.7 on 2024-07-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userModel", "0003_alter_reguser_gender_alter_reguser_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="reguser",
            name="logintimes",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
