# Generated by Django 5.0.7 on 2024-07-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userModel", "0004_reguser_logintimes"),
    ]

    operations = [
        migrations.AddField(
            model_name="reguser",
            name="qq",
            field=models.CharField(default="000001", max_length=20),
            preserve_default=False,
        ),
    ]
