# Generated by Django 5.0.7 on 2024-07-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userModel", "0005_reguser_qq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reguser",
            name="logintimes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="reguser",
            name="qq",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
