# Generated by Django 5.2 on 2025-07-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModel', '0006_alter_reguser_logintimes_alter_reguser_qq'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='is_Active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
