# Generated by Django 5.2 on 2025-07-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModel', '0006_alter_reguser_logintimes_alter_reguser_qq'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='reguser',
            name='lastlogin',
            field=models.DateTimeField(default='2025-7-17'),
            preserve_default=False,
        ),
    ]
