# Generated by Django 5.2 on 2025-07-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testForTeaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logintimes', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=20)),
                ('qq', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=10)),
                ('birthdate', models.DateField()),
                ('nativePlace', models.CharField(max_length=20)),
                ('regdate', models.DateTimeField()),
                ('is_Active', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
